#2 - Only collect button events within the same channel
kalempster/discord.js-menu-buttons pull request #3
Opened 2022-12-28 05:18 UTC by FivePixels

2023-01-05 19:25 UTC, kalempster requested changes
We also need to change the `index.ts` so in the future the source will match the compiled JS file.

2023-01-05 19:26 UTC, FivePixels commented
Good call, when I made this I had forgotten that typescript is just compiled JS.

2023-01-06 09:54 UTC, kalempster approved these changes

2023-01-06 09:55 UTC, kalempster commented
Also good catch, I initially didn't think of that scenario so I just left the filter

2023-01-06 09:55 UTC, merged